### ISSUE TITLE
-think

### ISSUE THREAD

**Issue by 404-404** [UnrealKaraulov/RERUNEMOD#1]
https://github.com/UnrealKaraulov/RERUNEMOD/blob/49413b9c4b901a00d709e1752c6ca3bdb755fa16/rm_teleport_rune.sma#L124

Юзай primaryAttack для ножа

**Comment by UnrealKaraulov** [comment]
@404-404 Готово в https://github.com/UnrealKaraulov/RERUNEMOD/commit/44b439f05c3ef92464804c7da6572a15b924e198 все руны с THINK оптимизированы!
