### ISSUE TITLE
About mod support continuation and installation error

### ISSUE THREAD

**Issue by ZewZack** [UnrealKaraulov/RERUNEMOD#2]
Hello bro. Love your work. I did exactly what you said one by one. 

installed amxmodx 1.9
installed reapi latest with include
complied plugins
copied plugins-RunemodReloaded.ini to /addons/amxmodx/configs/
copied all files to /cstrike/
changed map and all plugins give this error: NO BASE FUNC FOUND

![error](https://github.com/UnrealKaraulov/RERUNEMOD/assets/54986847/72afeab0-9d35-487c-b159-790dc5179421)

Can't find any fix on anywhere bro. I would be very grateful if you can help me. I really want to play this mod after a long time.

**Comment by UnrealKaraulov** [comment]
Need install rm_base (main plugin) in not first position, sorry for this bug, need install it after admins and other plugins )

Or need use plugins-RunemodReloaded.ini to install this.

**Comment by UnrealKaraulov** [comment]
@ZewZack
